### ISSUE TITLE
Update to Jakarta EE8 APIs for MP 3.3 in Feb 2020

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse/microprofile-context-propagation#183]

**Comment by njr-11** [comment]
The only references that we could find to Java EE in this spec were in the compile dependencies for the TCK (fixed under #184).  I also noticed an issue #172 to exclude EL from the CDI dependency which we can also clean up here. I created pull #185 for that.

If these are all the changes to make for Jakarta EE, then I wonder if we should consider just a micro version update (to 1.0.2) rather than minor version update to 1.1.  Anyone who is compiling against MP Context Propagation or running against it with Jakarta EE 8 would be able to use the original MP Context Propagation 1.0 just fine without any changes.  The only impact that I am aware of would be to someone who wants to compile the TCK or run against it with Jakarta EE 8 API as a dependency rather than Java EE 8.  Is there any reason why we wouldn't just create a 1.0.2 micro version update to the TCK for this, similar to how we created the 1.0.1 micro version update to make the TCK more lenient without any actual changes to spec function?

**Comment by manovotn** [comment]
Micro is fine IMO, the APIs should be exactly the same, so not much change there.
But if all other MP spec do minor version, then we might as well follow that.
The real "fun" begins when MP gets to switch to newer ones where `javax` packages change `jakarta` packages :-D

**Comment by njr-11** [comment]
The [1.0.2](https://github.com/eclipse/microprofile-context-propagation/releases/tag/1.0.2) micro release now covers Jakarta EE 8, so I'm closing this issue.

**Comment by kenfinnigan** [comment]
Not sure if this needs to be re-opened, but it was decided in MP Hangout today that Jakarta EE update will be done for MP 4.0 in June

**Comment by njr-11** [comment]
As far as I know that doesn't change anything for MP Context Propagation.  Version 1.0.2 already supports Jakarta EE 8 (which just amounts to pointing at Jakarta for TCK dependencies), as will subsequent releases made after this point.
